version: '3.9'

services:
  vircadia-mongodb:
    image: vircadia-mongodb:4.4
    container_name: vircadia-mongodb
    restart: unless-stopped
    hostname: vircadia-mongodb
    ports:
      - 27020:27020
    command: [--auth]
    volumes:
      - ./data/vircadia-mongo/db:/data/db
      - ./data/vircadia-mongo/log:/var/log/mongodb
    networks:
      - vircadia

  vircadia-metaverse-server:
    image: metaverse-server:latest
    container_name: vircadia-metaverse-server
    restart: unless-stopped
    hostname: vircadia-metaverse-server
    environment:
      - IAMUS_CONFIG_FILE=/home/cadia/config/iamus.json
    volumes:
      - ./files/metaverse/iamus.json:/home/cadia/config/iamus.json
      - ./data/vircadia-metaverse/metaverse/logs:/home/cadia/vircadia-metaverse/logs
      - ./data/vircadia-metaverse/metaverse/Logs:/home/cadia/vircadia-metaverse/Logs
    ports:
      - 9400:9400
    links:
      - vircadia-mongodb
    networks:
      - vircadia
    depends_on:
      - vircadia-mongodb

  vircadia-metaverse-dashboard:
    image: metaverse-dashboard:latest
    container_name: vircadia-metaverse-dashboard
    restart: unless-stopped
    hostname: vircadia-metaverse-dashboard
    volumes:
      - ./data/vircadia-metaverse-dashboard/logs:/home/cadia/metaverse-dashboard/log
    # ports:
    #   - 8088:8088
    links:
      - vircadia-metaverse-server
    networks:
      - vircadia
    depends_on:
      - vircadia-metaverse-server

  vircadia-ice-server:
    image: vircadia-domain-server:latest
    container_name: vircadia-ice-server
    restart: unless-stopped
    hostname: vircadia-ice-server
    # ports:
    #   - 7337:7337
    #   - 7337:7337/udp
    environment:
      - METAVERSE_URL=https://metaverse.innoxai.com
    entrypoint: /home/cadia/start-ice-server.sh
    volumes:
      - ./data/vircadia-ice-server/server-dotlocal/testmeteverse:/home/cadia/.local
      - ./data/vircadia-ice-server/server-logs/testmeteverse:/home/cadia/logs
    networks:
      - vircadia
    links:
      - vircadia-metaverse-server
    depends_on:
      - vircadia-metaverse-server

  vircadia-domain-server:
    image: vircadia-domain-server:latest
    container_name: vircadia-domain-server
    restart: unless-stopped
    hostname: vircadia-domain-server
    # ports:
    #   - 40100-40102:40100-40102
    #   - 40100-40102:40100-40102/udp
    #   - 48000-48009:48000-48009/udp
    environment:
      - METAVERSE_URL=https://metaverse.innoxai.com
      - ICE_SERVER=https://ice.innoxai.com
      - CLEANNAME=vircadia-metaverse-server
      - DOCKER_REPOSITORY=local
      - IMAGE_NAME=vircadia-domain-server
      - IMAGE_VERSION=l
      - INSTANCE=0
    volumes:
      - ./data/vircadia-domain-server/server-dotlocal/testmeteverse:/home/cadia/.local
      - ./data/vircadia-domain-server/server-logs/testmeteverse:/home/cadia/logs
    links:
      - vircadia-metaverse-server
    networks:
      - vircadia
    depends_on:
      - vircadia-ice-server

  vircadia-web:
    image: vircadia-web:latest
    container_name: vircadia-web
    restart: unless-stopped
    hostname: vircadia-web
    # ports:
    #   - 8080:8080
    volumes:
      - ./data/vircadia-web/logs:/home/cadia/vircadia-web/log
    links:
      - vircadia-metaverse-server
    networks:
      - vircadia
    depends_on:
      - vircadia-domain-server

  vircadia-nginx:
    image: vircadia-nginx
    container_name: vircadia-nginx
    restart: unless-stopped
    volumes:
      - ./files/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./files/nginx/vircadia.conf:/etc/nginx/http.d/vircadia.conf
      # - ./files/nginx/vircadia-mongodb.conf:/etc/nginx/stream.d/vircadia-mongodb.conf
      - ./data/vircadia-nginx/logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - vircadia
    depends_on:
      - vircadia-domain-server

networks:
  vircadia:
    driver: bridge
